### ISSUE TITLE
[DECOMPOSE] Phase 1: Test Categorization & Fast Feedback Pipeline

### ISSUE THREAD

**Issue by krhrtky** [krhrtky/open-api-code-generator#32]
# [DECOMPOSE] Phase 1: Test Categorization & Fast Feedback Pipeline

## 🎯 目的
全てのTypeScriptテストを実行時間と重要度で分類し、PR検証用の高速フィードバックパイプラインを構築する。

### Test Category Analysis & Classification
- [ ] **Analyze current test execution times**
  - Measure individual test file execution times
  - Identify slow test bottlenecks (>10s)
  - Create test execution time baseline

- [ ] **Categorize tests by speed and criticality**
  ```typescript
  // Test Categories
  Fast Tests (0-5s):
  - unit tests (validation.test.ts)
  - basic integration (parser basic tests)
  - type checking tests
  
  Medium Tests (5-30s):
  - feature integration tests
  - async-processor.test.ts (optimized)
  - external-resolver.test.ts
  
  Slow Tests (30s+):
  - large-spec-performance.test.ts
  - benchmark.test.ts
  - stress tests
  ```

### Fast Feedback Pipeline Implementation  
- [ ] **Create fast test suite configuration**
  ```javascript
  // jest.fast.config.js
  module.exports = {
    ...require('./jest.config.js'),
    testPathIgnorePatterns: [
      '<rootDir>/src/__tests__/large-spec-performance.test.ts',
      '<rootDir>/src/__tests__/benchmark.test.ts',
      '<rootDir>/src/__tests__/*performance*.test.ts'
    ],
    maxWorkers: '75%',
    bail: 1, // Fail fast
    timeout: 15000 // 15s timeout for fast tests
  };
  ```

- [ ] **Add npm scripts for different test modes**
  ```json
  {
    "scripts": {
      "test:fast": "jest --config jest.fast.config.js",
      "test:medium": "jest --config jest.medium.config.js",
      "test:slow": "jest --config jest.slow.config.js",
      "test:pr": "npm run lint && npm run typecheck && npm run test:fast"
    }
  }
  ```

### Change Detection & Selective Testing
- [ ] **Implement file dependency mapping**
  ```typescript
  // test-impact-analysis.js
  const testMapping = {
    'src/parser.ts': ['parser.test.ts', 'integration.test.ts'],
    'src/generator.ts': ['generator.test.ts', 'integration.test.ts'],
    'src/validation.ts': ['validation.test.ts', 'property-based-validation.test.ts']
  };
  ```

- [ ] **Create smart test selection script**
  ```bash
  #\!/bin/bash
  # scripts/run-affected-tests.sh
  CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
  AFFECTED_TESTS=$(node scripts/get-affected-tests.js "$CHANGED_FILES")
  jest $AFFECTED_TESTS
  ```

### Early Failure Detection
- [ ] **Implement critical path validation**
  - Lint errors → immediate failure
  - Type errors → immediate failure  
  - Core unit test failures → immediate failure
  - Dependency issues → immediate failure

- [ ] **Setup test ordering by criticality**
  ```javascript
  // test-sequencer.js
  const Sequencer = require('@jest/test-sequencer').default;
  
  class CustomSequencer extends Sequencer {
    sort(tests) {
      const criticalTests = tests.filter(test => 
        test.path.includes('validation') || 
        test.path.includes('parser')
      );
      const otherTests = tests.filter(test => \!criticalTests.includes(test));
      return [...criticalTests, ...otherTests];
    }
  }
  ```

## 🛠️ GitHub Actions Fast Pipeline
```yaml
# .github/workflows/fast-feedback.yml
name: Fast Feedback Pipeline
on: [pull_request]

jobs:
  fast-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run fast validation
        run: |
          npm run lint
          npm run typecheck
          npm run test:fast
        
      - name: Early feedback comment
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Fast validation failed. Please check lint, type, and core tests.'
            });

  comprehensive-tests:
    needs: fast-validation
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'full-ci')
    steps:
      - name: Run comprehensive test suite
        run: npm test
```

## ✅ Done の定義
- [ ] All tests are categorized by execution time
- [ ] Fast test suite completes in <30 seconds
- [ ] PR validation pipeline provides feedback in <2 minutes
- [ ] Change detection correctly identifies affected tests
- [ ] Critical path tests run first and fail fast
- [ ] GitHub Actions fast pipeline is implemented
- [ ] npm scripts for different test modes are available
- [ ] Documentation for test categories is created

## 📊 Performance Targets
- **Fast Test Suite**: <30 seconds total execution
- **PR Validation**: <2 minutes end-to-end
- **Critical Path**: <15 seconds for core validations
- **Change Detection**: 90%+ accuracy in affected test identification

## 🔗 Parent Issue
- Issue #31: [EPIC] TypeScript CI Performance Optimization

---
**Assignee**: @worker
**Priority**: High
**Estimated Time**: 2-3 days
**Status**: Ready for Work
