### ISSUE TITLE
[ENHANCEMENT] Add Codecov Integration for Test Coverage Reporting

### ISSUE THREAD

**Issue by krhrtky** [krhrtky/open-api-code-generator#45]
# [ENHANCEMENT] Add Codecov Integration for Test Coverage Reporting

## 🎯 目的
Codecovを使用してテストカバレッジの自動集計・可視化を実現し、mainブランチとPull Requestの両方でカバレッジ状況を追跡可能にする。

### Rust Implementation Coverage
- [ ] **cargo-tarpaulin** の設定とCI統合
- [ ] **src/parser.rs** カバレッジ測定
- [ ] **src/generator.rs** カバレッジ測定  
- [ ] **src/errors.rs** カバレッジ測定
- [ ] **src/types.rs** カバレッジ測定
- [ ] **統合テスト** カバレッジ測定

### CI/CD Integration
- [ ] **GitHub Actions** でのカバレッジ生成
- [ ] **Codecov Upload Action** の設定
- [ ] **mainブランチ** での自動カバレッジ追跡
- [ ] **Pull Request** でのカバレッジ比較
- [ ] **カバレッジ低下防止** のチェック設定

### Configuration Files
- [ ] **codecov.yml** 設定ファイル作成
- [ ] **カバレッジ閾値** の設定（目標: 85%以上）
- [ ] **除外パターン** の設定（tests/, target/等）
- [ ] **PR Status Check** の有効化

### 1. GitHub Actions Workflow更新
```yaml
# .github/workflows/ci.yml に追加
- name: Generate coverage report
  run: |
    cargo install cargo-tarpaulin
    cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml

- name: Upload coverage to Codecov
  uses: codecov/codecov-action@v4
  with:
    file: ./cobertura.xml
    flags: rust
    name: rust-coverage
    fail_ci_if_error: true
```

### 2. Codecov Configuration
```yaml
# codecov.yml
coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 1%
    patch:
      default:
        target: 85%
        threshold: 1%
  
ignore:
  - "tests/"
  - "target/"
  - "generated_rust/"
  - "**/*.md"
```

### 3. Badge Integration
```markdown
# README.md に追加
[![codecov](https://codecov.io/gh/krhrtky/open-api-code-generator/branch/main/graph/badge.svg)](https://codecov.io/gh/krhrtky/open-api-code-generator)
```

### Coverage Metrics
- **Overall Coverage**: 85%以上
- **src/parser.rs**: 90%以上（既存の充実したテスト）
- **src/generator.rs**: 85%以上（Issue #27完了後）
- **src/errors.rs**: 95%以上（エラーハンドリング重要）
- **src/types.rs**: 90%以上（型安全性重要）

### Integration Benefits
- **可視化**: カバレッジ状況のリアルタイム追跡
- **品質保証**: PR毎のカバレッジ変化確認
- **自動化**: CI/CDパイプラインでの自動測定
- **透明性**: 外部からのカバレッジ状況確認

## ✅ Done の定義
- [ ] cargo-tarpaulinがCI/CDで正常動作
- [ ] CodecovでRustカバレッジが正確に表示
- [ ] mainブランチのカバレッジが追跡されている
- [ ] Pull Requestでカバレッジ差分が表示される
- [ ] codecov.ymlで適切な閾値設定が動作
- [ ] READMEにカバレッジバッジが表示
- [ ] カバレッジ85%以上を維持

## 🔗 関連Issue
- Issue #25: [EPIC] Rust Test Coverage Enhancement
- Issue #26: ✅ OpenAPIParser Unit Tests Implementation
- Issue #27: 🚧 OpenAPICodeGenerator Unit Tests Implementation  
- Issue #28: ✅ Error Handling & Type System Tests

## 📈 Implementation Priority
**Priority**: High
**Estimated Time**: 4-6 hours
**Status**: Ready for Work
**Assignee**: @developer

---
**Note**: この実装により、プロジェクトの品質可視化とテストカバレッジの継続的な改善が可能になります。
